// <auto-generated />
namespace pathos.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fix001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix001));
        
        string IMigrationMetadata.Id
        {
            get { return "201405282207413_fix001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
